# jaeger
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-jaeger
spec:
  serviceName: {{ .Release.Name }}-jaeger
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jaeger
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jaeger
    spec:
      containers:
        - name: jaeger
          image: {{ include "helm.image" (dict "imageConfig" .Values.images.jaeger "global" .Values.global) }}
          imagePullPolicy: "{{ .Values.images.jaeger.pullPolicy }}"
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 6831
            - containerPort: 14268
            - containerPort: 16686
          volumeMounts:
            - name: jaeger-data
              mountPath: /badger
      {{- if not .Values.persistence.jaeger.enabled }}
      volumes:
        - name: jaeger-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.jaeger.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: jaeger-data
      spec:
        accessModes:
          - {{ .Values.persistence.jaeger.accessMode }}
        {{- if .Values.persistence.jaeger.storageClass }}
        storageClassName: {{ .Values.persistence.jaeger.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.jaeger.size }}
  {{- end }}

---
# redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
spec:
  serviceName: {{ .Release.Name }}-redis
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: {{ include "helm.image" (dict "imageConfig" .Values.images.redis "global" .Values.global) }}
          imagePullPolicy: "{{ .Values.images.redis.pullPolicy }}"
          ports:
            - containerPort: 6379
          {{- if not .Values.persistence.redis.enabled }}
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.persistence.redis.enabled }}
      volumes:
        - name: redis-data
          emptyDir:
            medium: "Memory"
            sizeLimit: "512Mi"
      {{- end }}
  {{- if .Values.persistence.redis.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - {{ .Values.persistence.redis.accessMode }}
        {{- if .Values.persistence.redis.storageClass }}
        storageClassName: {{ .Values.persistence.redis.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.redis.size }}
  {{- end }}

---
# mysql
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  serviceName: {{ .Release.Name }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: mysql
          image: {{ include "helm.image" (dict "imageConfig" .Values.images.mysql "global" .Values.global) }}
          imagePullPolicy: "{{ .Values.images.mysql.pullPolicy }}"
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          env:
            - name: MYSQL_DATABASE
              value: "{{ .Values.configmap.database.mysql.db }}"
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.configmap.database.mysql.password }}"
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            {{- if not .Values.persistence.mysql.enabled }}
            - --innodb-flush-log-at-trx-commit=2
            - --innodb-buffer-pool-size=256M
            - --innodb-log-file-size=32M
            - --skip-innodb-doublewrite
            - --innodb-flush-method=O_DIRECT_NO_FSYNC
            {{- end }}
          ports:
            - containerPort: 3306
          {{- if not .Values.persistence.mysql.enabled }}
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          {{- end }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      {{- if not .Values.persistence.mysql.enabled }}
      volumes:
        - name: mysql-data
          emptyDir:
            medium: "Memory"
            sizeLimit: "1Gi"
      {{- end }}
  {{- if .Values.persistence.mysql.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - {{ .Values.persistence.mysql.accessMode }}
        {{- if .Values.persistence.mysql.storageClass }}
        storageClassName: {{ .Values.persistence.mysql.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.mysql.size }}
  {{- end }}
