# settings.toml

[default]
default_port = 30080
generator_image = "docker.io/opspai/openapi-generator-cli:1.0.0"
k8s_namespace = "exp"
release_name = "rcabench"
python_sdk_dir = "sdk/python"
time_format = "%Y%m%d_%H%M%S"

[default.database.mysql]
host = "localhost"
port = "3306"
user = "root"
password = "yourpassword"
db = "rcabench"

[default.redis]
host = "localhost"
port = "6379"


[dev]
default_repo = "10.10.10.240/library/rcabench"

[prod]
default_repo = "pair-diag-cn-guangzhou.cr.volces.com/pair"

[prod.database.mysql]
host = "localhost"
port = "13306"

[prod.redis]
host = "localhost"
port = "16379"
