global:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair
    tag: "v1.2.9"
  security:
    allowInsecureImages: true

mysql:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair/mysql

rabbitmq:
  image:
    registry: pair-diag-cn-guangzhou.cr.volces.com/pair
    repository: rabbitmq

loadgenerator:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair/loadgenerator
  initContainer:
    image: pair-diag-cn-guangzhou.cr.volces.com/pair/netshoot:v0.14
