name = "AegisLab"
version = "1.1.47"

port = 8082
workspace = "/home/nn/workspace/AegisLab"

[system]
env_mode = "dev"
timezone = "Asia/Shanghai"

[initialization]
data_path = "/home/nn/workspace/AegisLab/helm/files/initial_data"

[debugging]
enable = true

[injection]
target_label_key = "app"

[injection.namespace_config.ts]
count = 1

[database]
clickhouse_host = "10.10.10.58"
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "rcabench"

[jaeger]
endpoint = "localhost:4318"

[redis]
host = "localhost:6379"

[harbor]
registry = "10.10.10.240"
namespace = "library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "exp"
context_env_key = "DEV_CONTEXT"

[k8s.init_container]
busybox_image = "10.10.10.240/library/busybox:1.35"

[k8s.job.volume_mount.kube_config]
name = "kube-config"
mount_path = "/root/.kube/config"
sub_path = "config"
source_type = "secret"
secret_name = "kube-config"

[k8s.job.volume_mount.dataset]
name = "dataset"
mount_path = "/data"
source_type = "pvc"
claim_name = "rcabench-juicefs-dataset"

[k8s.job.volume_mount.experiment_storage]
name = "experiment-storage"
mount_path = "/experiment_storage"
source_type = "pvc"
claim_name = "rcabench-juicefs-experiment-storage"


[logging]
dir = "/home/nn/workspace/AegisLab/logs"

[logging.job]
dir = "jobs"
log_retention_days = 7

[jfs]
dataset_path = "/mnt/jfs/rcabench_dataset"
experiment_storage_path = "/mnt/jfs/experiment_storage"

[algo]
detector = "detector_harbor"

[container]
storage_path = "/home/nn/workspace/AegisLab/containers"

[buildkit]
address = "localhost:1234"

[rate_limiting]
max_concurrent_builds = 3
max_concurrent_restarts = 2
max_concurrent_algo_execution = 5
token_wait_timeout = 10
