name = "AegisLab"
version = "1.1.49"

port = 8080
workspace = "/app"

[system]
env_mode = "dev"
timezone = "Asia/Shanghai"

[initialization]
data_path = "/data/initial_data"

[debugging]
enable = true

[injection]
benchmark = ["clickhouse"]
target_label_key = "app"

[injection.namespace_config.ts]
count = 1

[database.clickhouse]
port = "8123"
host = "10.10.10.58"
user = "app"
password = "hyperdx"
db = "default"
timezone = "Asia/Shanghai"

[database.mysql]
host = "localhost"
port = "3306"
user = "root"
password = "yourpassword"

[jaeger]
endpoint = "test-jaeger:4318"

[redis]
host = "test-redis:6379"

[harbor]
registry = "10.10.10.240"
namespace = "library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "exp"
[k8s.service]
internal_url = "http://rcabench-exp:8082"

[k8s.init_container]
busybox_image = "10.10.10.240/library/busybox:1.35"

[k8s.job.service_account]
name = "rcabench-sa"

[k8s.job.volume_mount.dataset]
name = "dataset"
mount_path = "/data"
source_type = "pvc"
claim_name = "rcabench-juicefs-dataset"

[k8s.job.volume_mount.experiment_storage]
name = "experiment-storage"
mount_path = "/experiment_storage"
source_type = "pvc"
claim_name = "rcabench-juicefs-experiment-storage"

[logging]
dir = "/app/logs"

[logging.job]
dir = "jobs"
log_retention_days = 7

[algo]
detector = "detector"

[container]
storage_path = "/app/containers"

[buildkit]
address = "test-buildkitd:1234"

[rate_limiting]
max_concurrent_builds = 3
max_concurrent_restarts = 2
max_concurrent_algo_execution = 5
token_wait_timeout = 10
