name = "AegisLab"
version = "1.1.55"

port = 8082
workspace = "/home/nn/workspace/AegisLab"

[system]
timezone = "Asia/Shanghai"

[initialization]
data_path = "/home/nn/workspace/AegisLab/data/initial_data"

[database.mysql]
host = "localhost"
port = "3306"
user = "root"
password = "yourpassword"
db = "rcabench"

[jaeger]
endpoint = "localhost:4318"

[redis]
host = "localhost:6379"

[k8s]
namespace = "exp"

[k8s.service]
internal_url = "http://10.10.10.161:8082"

[k8s.init_container]
busybox_image = "10.10.10.240/library/busybox:1.35"

[k8s.job.service_account]
name = "rcabench-sa"

[k8s.job.volume_mount.dataset]
name = "dataset"
mount_path = "/data"
source_type = "pvc"
claim_name = "rcabench-juicefs-dataset"

[k8s.job.volume_mount.experiment_storage]
name = "experiment-storage"
mount_path = "/experiment_storage"
source_type = "pvc"
claim_name = "rcabench-juicefs-experiment-storage"

[logging]
dir = "/home/nn/workspace/AegisLab/logs"

[logging.job]
dir = "jobs"

[jfs]
dataset_path = "/mnt/jfs/rcabench_dataset"
experiment_storage_path = "/mnt/jfs/experiment_storage"

[container]
storage_path = "/home/nn/workspace/AegisLab/containers"

[buildkit]
address = "localhost:1234"
