name: Build Make Command Tool

on:
    push:
        paths:
            - "scripts/command/src/**.py"
            - "scripts/command/main.py"
            - "scripts/command/pyproject.toml"
        tags-ignore:
            - "*"

    workflow_dispatch:

jobs:
    build-make-command:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true

            - name: Install dependencies
              run: |
                  sudo apt-get update && sudo apt-get install -y patchelf ccache

            - name: Build Make command tool
              run: |
                  make build-make-command

            - name: Upload Make command tool artifact
              uses: actions/upload-artifact@v4
              with:
                  name: make-command-tool
                  path: scripts/command/command.bin
                  retention-days: 7
